name: Docker push
description: "Docker action to push image into registry"

inputs:
  DOCKERHUB_USERNAME:
    description: "Docker username"
  IMAGE_NAME:
    description: "Docker image name"
runs:
  using: "composite"
  steps:
    - name: Prep image tag
      run:  docker image tag ${{inputs.IMAGE_NAME}} ${{inputs.DOCKERHUB_USERNAME}}${{inputs.IMAGE_NAME}}
      shell: bash
    - name: Push image to registry
      run: docker image push ${{inputs.DOCKERHUB_USERNAME}}//${{inputs.IMAGE_NAME}}
      shell: bash
